markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /posts/:title.html
auto: true
title: Pan's Blog
author:
  name: Pan Liu
  email: liupan1111@gmail.com
  github: liupan1111

production_url: http://blog.wjin.org

baseurl: /
