markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /posts/:title.html
auto: true
title: Eric's Blog
author:
  name: Eric
  email: wjin.cn@gmail.com
  github: wjin

production_url: http://blog.wjin.org

baseurl: /
